### ISSUE TITLE
Redirect vue-apollo.netlify.com to apollo.vuejs.org

### ISSUE THREAD

**Issue by bluwy** [vuejs/vue-apollo#945]
**Is your feature request related to a problem? Please describe.**
Both https://vue-apollo.netlify.com and https://apollo.vuejs.org seems to be identical. But for newcomers, the two websites might confuse them on which is the most up-to-date or official version.

**Describe the solution you'd like**
It would be great to do a 301 redirect from https://vue-apollo.netlify.com to https://apollo.vuejs.org. [Netlify's docs](https://docs.netlify.com/routing/redirects/) made it really easy to perform the redirect. In short, the redirect can be done by adding a `netlify.toml` file at the docs root with contents:

```toml
[[redirects]]
  from = "https://vue-apollo.netlify.com/*"
  to = "https://apollo.vuejs.org/:splat"
  status = 301
  force = true
```

**Additional context**
This should not have any impact on SEO. Hope to have this be considered :)
